/**
 * Mock Data for Kenyan Street Food Rider App
 * Contains delivery jobs, earnings, and rider information
 */

export const mockDeliveryJobs = [
  {
    id: 'JOB001',
    orderId: 'ORD001',
    vendorName: 'Mama Kariuki\'s Nyama Choma',
    vendorLocation: { latitude: -1.2865, longitude: 36.8172 },
    customerName: 'John Doe',
    customerLocation: { latitude: -1.2900, longitude: 36.8200 },
    customerPhone: '+254712345678',
    items: ['Nyama Choma (500g)', 'Kachumbari'],
    totalAmount: 400,
    distance: 2.5,
    estimatedTime: 15,
    paymentMethod: 'cash',
    status: 'available',
    createdAt: new Date(Date.now() - 5 * 60 * 1000),
    earnings: 80,
  },
  {
    id: 'JOB002',
    orderId: 'ORD002',
    vendorName: 'Samosa King',
    vendorLocation: { latitude: -1.2875, longitude: 36.8182 },
    customerName: 'Jane Smith',
    customerLocation: { latitude: -1.2850, longitude: 36.8150 },
    customerPhone: '+254723456789',
    items: ['Samosa (3 pieces)', 'Mandazi (4 pieces)'],
    totalAmount: 130,
    distance: 1.8,
    estimatedTime: 12,
    paymentMethod: 'mpesa',
    status: 'available',
    createdAt: new Date(Date.now() - 2 * 60 * 1000),
    earnings: 60,
  },
  {
    id: 'JOB003',
    orderId: 'ORD003',
    vendorName: 'Githeri Express',
    vendorLocation: { latitude: -1.2855, longitude: 36.8162 },
    customerName: 'Peter Kipchoge',
    customerLocation: { latitude: -1.2920, longitude: 36.8220 },
    customerPhone: '+254734567890',
    items: ['Githeri (Large)', 'Sukuma Wiki'],
    totalAmount: 170,
    distance: 3.2,
    estimatedTime: 18,
    paymentMethod: 'cash',
    status: 'available',
    createdAt: new Date(Date.now() - 1 * 60 * 1000),
    earnings: 100,
  },
  {
    id: 'JOB004',
    orderId: 'ORD004',
    vendorName: 'Mandazi & Tea House',
    vendorLocation: { latitude: -1.2885, longitude: 36.8192 },
    customerName: 'Mary Wanjiru',
    customerLocation: { latitude: -1.2880, longitude: 36.8180 },
    customerPhone: '+254745678901',
    items: ['Mandazi (4 pieces)', 'Tea (Large)', 'Chapati'],
    totalAmount: 120,
    distance: 0.8,
    estimatedTime: 8,
    paymentMethod: 'mpesa',
    status: 'available',
    createdAt: new Date(Date.now() - 10 * 60 * 1000),
    earnings: 50,
  },
  {
    id: 'JOB005',
    orderId: 'ORD005',
    vendorName: 'Ugali & Sukuma Wiki',
    vendorLocation: { latitude: -1.2845, longitude: 36.8152 },
    customerName: 'David Kiplagat',
    customerLocation: { latitude: -1.2870, longitude: 36.8190 },
    customerPhone: '+254756789012',
    items: ['Ugali & Sukuma Wiki', 'Beans & Ugali'],
    totalAmount: 190,
    distance: 2.1,
    estimatedTime: 14,
    paymentMethod: 'cash',
    status: 'available',
    createdAt: new Date(Date.now() - 8 * 60 * 1000),
    earnings: 70,
  },
];

export const mockCompletedDeliveries = [
  {
    id: 'JOB001-COMPLETED',
    orderId: 'ORD001',
    vendorName: 'Mama Kariuki\'s Nyama Choma',
    customerName: 'Alice Johnson',
    totalAmount: 450,
    earnings: 90,
    completedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    rating: 5,
    review: 'Great service, very fast!',
  },
  {
    id: 'JOB002-COMPLETED',
    orderId: 'ORD002',
    vendorName: 'Samosa King',
    customerName: 'Bob Wilson',
    totalAmount: 200,
    earnings: 75,
    completedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    rating: 4,
    review: 'Good delivery time',
  },
  {
    id: 'JOB003-COMPLETED',
    orderId: 'ORD003',
    vendorName: 'Githeri Express',
    customerName: 'Carol Davis',
    totalAmount: 320,
    earnings: 85,
    completedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    rating: 5,
    review: 'Excellent rider!',
  },
];

export const mockRiderProfile = {
  id: 'RIDER001',
  name: 'John Mwangi',
  phoneNumber: '+254712345678',
  email: 'john@example.com',
  profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
  idNumber: '12345678',
  vehicleType: 'Bodaboda',
  vehicleNumber: 'KBZ 123A',
  rating: 4.8,
  totalDeliveries: 234,
  totalEarnings: 45600,
  joinedDate: new Date('2023-06-15'),
  isVerified: true,
  bankAccount: 'John Mwangi - 254712345678',
};

export const mockEarningsData = {
  today: 450,
  thisWeek: 2800,
  thisMonth: 12500,
  total: 45600,
  pendingWithdrawal: 0,
  lastWithdrawal: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
};

export const mockNotifications = [
  {
    id: 1,
    type: 'job_available',
    title: 'New Delivery Job',
    message: 'High-paying order from Mama Kariuki\'s Nyama Choma',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    read: false,
  },
  {
    id: 2,
    type: 'job_completed',
    title: 'Delivery Completed',
    message: 'You earned KSh 90 from your last delivery',
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    read: true,
  },
  {
    id: 3,
    type: 'rating',
    title: 'New Rating',
    message: 'Customer gave you 5 stars!',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: true,
  },
];

export const mockWithdrawalHistory = [
  {
    id: 'WD001',
    amount: 5000,
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    status: 'completed',
    mpesaRef: 'MPS123456789',
  },
  {
    id: 'WD002',
    amount: 3500,
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    status: 'completed',
    mpesaRef: 'MPS987654321',
  },
  {
    id: 'WD003',
    amount: 4200,
    date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    status: 'completed',
    mpesaRef: 'MPS456789123',
  },
];
